service: whisper
image: sebnun/langturbo-whisper

servers:
  web:
    hosts:
      - 34.26.13.75
    options:
      device: nvidia.com/gpu=all

volumes:
  - hf-hub-cache:/home/ubuntu/.cache/huggingface/hub

proxy:
  ssl: false
  app_port: 8000
  healthcheck:
    path: /health

registry:
  username: sebnun
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

ssh:
  user: pablo
