apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-podmonitor
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: postgres-cluster
  podMetricsEndpoints:
  - port: metrics