apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: langturbo
spec:
  instances: 1

  storage:
    size: 100Gi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-podmonitor
  namespace: langturbo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
  podMetricsEndpoints:
  - port: metrics